name: audio-hub
channels:
  - conda-forge

dependencies:
  # Core Python
  - python=3.12.4

  # Numeric/Scientific Stack
  - numpy=2.0.0
  - scipy=1.13.0
  - pandas=2.2.0

  # Audio Processing
  - librosa=0.10.1
  - pydub=0.25.1
  - soundfile=0.12.1
  - ffmpeg=6.1.1

  # Visualization/UI
  - matplotlib=3.8.3
  - ipywidgets=8.1.2
  - jupyterlab=4.0.10

  # System Libraries
  - libsndfile=1.2.2

  # Pip-only Packages
  - pip:
      - torch==2.2.1+cpu    # CPU-only wheel available for Python 3.12
      - pedalboard==0.7.1   # Audio effects
      - noisereduce==1.0.0  # Noise reduction
