name: audio-hub
channels:
  - conda-forge

dependencies:
  - python=3.11
  - numpy=1.26.4
  - scipy=1.10.1
  - pandas=2.0.3
  - librosa=0.10.1
  - pydub=0.25.1
  - ffmpeg=6.1.1
  - libsndfile=1.2.2
  - matplotlib=3.8.3
  - ipywidgets=8.1.2
  - jupyterlab=4.0.10
  - pip:
      - soundfile==0.12.1
      - torch==2.2.1
      - pedalboard==0.7.1
      - noisereduce==1.0.0
